## Copyright 2022 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

cloud: azure
organization: myOrg
name: projectmgt
systems:
  projects:
    - instanceName: ACM_ExampleProject
      templateName: azure-building-blocks/terraform/azdo-project
      tool: terraform
      repoName: ACM_ExampleCode
      sourceRepo: https://github.com/AgileCloudInstitute/agile-cloud-manager.git
      buildName: ACM_ExampleCode
      tfBackendStateFileName: projects.project.ACM_ExampleProject.tfstate
      endpointTemplate: azure-building-blocks/api/azdo-service-conn-other-git.json
  releaseDefinitions:
    - instanceName: ACM_DemoRelease
      projectName: ACM_ExampleProject
      vaultName: agentsVault
      YamlDefinitionFileName: ACM_DemoRelease.yaml
      repositories:
        - instanceName: ACM_ExampleCode