## Copyright 2022 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

cloud: azure
organization: myOrg
name: tfbackend
tags:
  networkName: name-of-vnet
  systemName: name-of-system
  environmentName: name-of-environment
  ownerName: name-of-owner
networkFoundation:
  instanceName: demo
  templateName: azure-building-blocks/terraform/found-tfbknd-az
  tool: terraform
  resourceGroupName: terraform-backend
  resourceGroupRegion: eastus
systems:
  tfBackend:
    - instanceName: adminAccounts
      templateName: azure-building-blocks/az-cli/storage-tfbknd-az
      type: azurerm
      tool: az-cli
      keyVaultName: adminAccountsBackend
      keyName: adminAccountsBackendKey
      environment: Dev
    - instanceName: pipelineAgents
      templateName: azure-building-blocks/az-cli/storage-tfbknd-az
      type: azurerm
      tool: az-cli
      keyVaultName: azdoAgentsBackend
      keyName: azdoAgentsBackendKey
      environment: Dev
    - instanceName: projectManagement
      templateName: azure-building-blocks/az-cli/storage-tfbknd-az
      type: azurerm
      tool: az-cli
      keyVaultName: projectManagementBackend
      keyName: projectManagementBackendKey
      environment: Dev