## Copyright 2022 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

cloud: azure
organization: myOrg
name: agents
tags:
  networkName: name-of-vnet
  systemName: name-of-system
  environmentName: name-of-environment
  ownerName: name-of-owner
networkFoundation:
  instanceName: demo
  templateName: azure-building-blocks/terraform/foundation
  tool: terraform
  resourceGroupName: azdo-agents
  resourceGroupRegion: eastus
  cidrSubnetPacker: 10.0.9.0/24
  tfBackendStorageContainerName: networkfoundation
  tfBackendStateFileName: agents.networkfoundation.tfstate
imageBuilds:
  images:
    - instanceName: RHEL73_AZDO_Agent
      templateName: azure-building-blocks/packer/rhel7-azure-arm-azdo-agent
      tool: packer
      ssh_user: packer
      ssh_pass: just-me-123
      init_script: \azure-building-blocks\scripts\rhel7-startup-azdo-agent.sh
systems:
  subnetsWithScaleSet:
    - instanceName: azdoAgents
      templateName: azure-building-blocks/terraform/snet-agents
      tool: terraform
      imageName: RHEL73_AZDO_Agent
      cidrSubnet: 10.0.6.0/24
      vmUserName: azureuser
      vmPwd: abc-some-pwd-123
      vaultName: agentsVault
      cloudInit: \azure-building-blocks\scripts\startup-script-demo.sh
      tfBackendStateFileName: agents.azdo-subnet.tfstate